# VSO Test — VaultStaticSecret syncing from Vault KV v2
# Reads secret/test from Vault and creates K8s Secret "vso-test" in security namespace.
# This validates the full VSO pipeline: VaultConnection → VaultAuth → KV read → K8s Secret.
#
# Verify with:
#   kubectl get secret vso-test -n security -o jsonpath='{.data.message}' | base64 -d
#   Expected: hello-from-vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vso-test
  namespace: security
spec:
  vaultAuthRef: default
  mount: secret
  type: kv-v2
  path: test
  refreshAfter: "60s"
  destination:
    name: vso-test
    create: true
    overwrite: true
  hmacSecretData: true
