# ArgoCD Server TLS Certificate
# Issued by Vault PKI intermediate CA via cert-manager.
# Auto-renewed 7 days before expiry.
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-tls
  namespace: argocd
spec:
  secretName: argocd-server-tls
  issuerRef:
    name: vault-pki
    kind: ClusterIssuer
  dnsNames:
    - argocd.mgmt.home.arpa
  duration: 360h    # 15 days (constrained by intermediate CA expiry 2026-03-20)
  renewBefore: 72h   # renew 3 days early
  privateKey:
    algorithm: RSA
    size: 2048
