# cert-manager ClusterIssuer — Vault PKI Integration
# Uses Kubernetes auth to request certificates from Vault's intermediate CA.
#
# Prerequisites (Vault side):
#   - PKI engine at pki_int/ with role "home-arpa-fqdns"
#   - Kubernetes auth enabled with role "cert-manager"
#   - Policy "cert-manager" allowing pki_int/sign/home-arpa-fqdns
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-pki
spec:
  vault:
    server: "https://vault.home.arpa:8200"
    path: "pki_int/sign/home-arpa-fqdns"
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLVENDQWhHZ0F3SUJBZ0lVV2dEcm5ob09VRkgvREpEYWthVm1NS0lhaXdvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0hERWFNQmdHQTFVRUF4TVJhRzl0WlM1aGNuQmhJRkp2YjNRZ1EwRXdIaGNOTWpZd01qRTJNVFF5TlRJMwpXaGNOTWpZd016SXdNVFF5TlRVM1dqQWNNUm93R0FZRFZRUURFeEZvYjIxbExtRnljR0VnVW05dmRDQkRRVENDCkFTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSml4eWJKVmthRUUxdXkwUjhDbXkyTmcKeWtTcWFsb3AxblFSeGNmWU9zWEJjdk82UVl5ZnptQktsQTNmS2p0N2RNZFgwZm95ODB2bmc3Q2xFdHNTUmxxSQpDbVpGQVI1T3FUNFpzSmthN0gzTDFZTmVIcStsR2ZrNlRFdkF0dGtVSVErSFgzZGFxcjRYczFySUFIdk1JNmI1CldDZTBrT3lzdnMrblZjQ3ZaY1A3UElDaUJpWGZ0UUw4RHRVRlRFSkxFTHRvekRLSDlPNXRHSnVObC92UmhCeXoKWktCOGwza3czTFNiMHl0QjllQjFHSkNZWDZFZVFWRzFSMjEzUE9aWnJQdUw0a29SUWk5UkdBTEh3VGhxWW5Gawo0VkcxakdSeHdkV0Z4Y1NEYTAzL21pRFg5QlI3UUUyaEJJdjZ1RUNGMWFRL2c5WWtzWFBqUExzUGo4M01pU1VDCkF3RUFBYU5qTUdFd0RnWURWUjBQQVFIL0JBUURBZ0VHTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME8KQkJZRUZNZ1NIRlo3SW1GQ3lzdm53Skp1aDBlZXEwOWJNQjhHQTFVZEl3UVlNQmFBRk1nU0hGWjdJbUZDeXN2bgp3Skp1aDBlZXEwOWJNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUI3UklJdXpqM1lHVEQxSnpCZEh4TkIrRFpSCktMd0IxSHgvT1R4dGFSem5seE9PRWZjclRZQTE3eFFBUWs1TUZtMXpEK0xKS0dQTi9USERoYXY2RjY1d2pySE8KWHk4UHVHd0xFQ3BEUTJQVk9nSGdwUDBKWFZkdFYxMERmb2RSUXpiSThBYy8wek5NSTdVRDY4UzdiREhSeHZZMQpHZTJNQnc5TStqYXFNUDMwQXNCL1dCQTBlM0crbW9BMFUrdEtmc25TNE50K0tad1lrVmx6NGsvMWZHK0RyNzllCmVSakthQjJkZUFZVGlIRnE0L3dOMDRjblFrTkkyeVh4SHZGbHN3d2pIYVB2aWdhZGIrbnpXS0hFbk5sTU0vQ3IKbytVYmFOcmpWUVQrQmxkSTQyRXlORXFqUW5YNmpjYVRrZTNEQzljWmU1NVBaRVhjaURtaEllYlRQRlIvCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    auth:
      kubernetes:
        role: cert-manager
        mountPath: /v1/auth/kubernetes
        serviceAccountRef:
          name: cert-manager
