# /etc/tmpfiles.d/certbot-dnsupd.conf
# Create runtime directory for certbot DNS-01 Kerberos credential caches.
# Cleared on reboot (tmpfs); recreated by systemd-tmpfiles-setup.service.
d /run/certbot-dnsupd 0700 root root -
