# HTTPRoute: longhorn.mgmt.home.arpa -> longhorn-frontend in longhorn-system
# HAProxy terminates TLS and enforces WireGuard-only ACL for *.mgmt.home.arpa,
# then forwards plain HTTP to the Gateway VIP. This route matches by hostname
# and forwards to the Longhorn UI service.
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: longhorn-ui
  namespace: longhorn-system
spec:
  parentRefs:
    - name: platform-gateway
      namespace: gateway-system
  hostnames:
    - "longhorn.mgmt.home.arpa"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: longhorn-frontend
          port: 80
          weight: 1
