# Allow Kubernetes API server to reach validating/mutating webhooks.
# Uses CiliumNetworkPolicy with fromEntities: kube-apiserver for precise
# eBPF-level identity matching — immune to SNAT, no IP guessing.
# This is the enterprise-grade approach for Cilium CNI clusters.
---
# MetalLB controller webhook (port 9443)
# Validates: IPAddressPool, L2Advertisement, BGPPeer, etc.
# MetalLB uses bare "component: controller" labels (NOT app.kubernetes.io/)
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-apiserver-webhook
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  endpointSelector:
    matchLabels:
      component: controller
  ingress:
    - fromEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "9443"
              protocol: TCP
---
# cert-manager webhook (port 10250)
# Validates: Certificate, Issuer, ClusterIssuer, etc.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-apiserver-webhook
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/component: "webhook"
  ingress:
    - fromEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "10250"
              protocol: TCP
---
# cert-manager controller (port 9402 — metrics endpoint)
# Kubelet liveness/readiness probes are implicitly allowed by Cilium.
# This rule exists for API-server-initiated health checks and future-proofing.
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-apiserver-controller
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/component: "controller"
  ingress:
    - fromEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "9402"
              protocol: TCP
