apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default-deny.yaml
  - allow-egress-core.yaml
  - allow-egress-services.yaml
  - allow-webhooks.yaml
  - allow-gateway-ingress.yaml
  - allow-kube-system.yaml
  - allow-spire.yaml
